-- ============================================================================
-- DATABASE SCHEMA - Decentralized Autonomous Forum
-- ============================================================================
-- Generated By: Design Agent
-- Date: 2025-10-21 19:00:00
-- Project: project-20251021-092500-decentralized-forum
-- Version: 1.0
-- Database: PostgreSQL 16+
-- Normalization: Third Normal Form (3NF)
--
-- Description:
-- Complete database schema for the Decentralized Autonomous Forum platform.
-- Includes 18 tables normalized to 3NF with proper indexes, constraints,
-- and triggers for data integrity.
--
-- ============================================================================

-- ============================================================================
-- ENTITY RELATIONSHIP DIAGRAM (ERD)
-- ============================================================================
--
--  ┌─────────────┐         ┌──────────────┐         ┌─────────────┐
--  │    users    │1      * │    posts     │1      * │  comments   │
--  │             ├─────────┤              ├─────────┤             │
--  │ • id (PK)   │         │ • id (PK)    │         │ • id (PK)   │
--  │ • email     │         │ • user_id(FK)│         │ • post_id FK│
--  │ • username  │         │ • title      │         │ • user_id FK│
--  │ • password  │         │ • body       │         │ • parent_id │
--  │ • points    │         │ • like_count │         │ • body      │
--  │ • level     │         │ • created_at │         │ • created_at│
--  └──────┬──────┘         └──────┬───────┘         └──────┬──────┘
--         │                       │                        │
--         │                       │                        │
--         │                       │                        │
--  ┌──────▼──────┐         ┌──────▼───────┐         ┌──────▼──────┐
--  │oauth_accounts│       │    likes     │         │   media     │
--  │             │         │              │         │             │
--  │ • id (PK)   │         │ • id (PK)    │         │ • id (PK)   │
--  │ • user_id FK│         │ • user_id FK │         │ • post_id FK│
--  │ • provider  │         │ • post_id FK │         │ • user_id FK│
--  │ • oauth_id  │         │ • comment_id │         │ • file_url  │
--  └─────────────┘         │ • created_at │         │ • ipfs_hash │
--                          └──────────────┘         └─────────────┘
--
--  ┌─────────────┐         ┌──────────────┐         ┌─────────────┐
--  │transactions │         │   reports    │         │    bans     │
--  │             │         │              │         │             │
--  │ • id (PK)   │         │ • id (PK)    │         │ • id (PK)   │
--  │ • user_id FK│         │ • reporter FK│         │ • user_id FK│
--  │ • amount    │         │ • content_id │         │ • banned_by │
--  │ • type      │         │ • reason     │         │ • reason    │
--  │ • reference │         │ • status     │         │ • until     │
--  └─────────────┘         └──────────────┘         └─────────────┘
--
--  ┌─────────────┐         ┌──────────────┐         ┌─────────────┐
--  │   levels    │         │   channels   │         │    tags     │
--  │             │         │              │         │             │
--  │ • id (PK)   │         │ • id (PK)    │         │ • id (PK)   │
--  │ • name      │         │ • name       │         │ • name      │
--  │ • min_points│         │ • description│         │ • post_count│
--  │ • permissions│        │ • created_at │         │ • created_at│
--  └─────────────┘         └──────────────┘         └─────────────┘
--
-- ============================================================================

-- ============================================================================
-- EXTENSIONS
-- ============================================================================

-- Enable UUID generation
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Enable full-text search
CREATE EXTENSION IF NOT EXISTS "pg_trgm";

-- Enable fuzzy string matching
CREATE EXTENSION IF NOT EXISTS "fuzzystrmatch";

-- ============================================================================
-- ENUMS
-- ============================================================================

CREATE TYPE user_level_enum AS ENUM (
    'new_user',         -- Level 0: 0-99 points
    'active_user',      -- Level 1: 100-499 points
    'trusted_user',     -- Level 2: 500-1,999 points
    'moderator',        -- Level 3: 2,000-9,999 points
    'senior_moderator', -- Level 4: 10,000-49,999 points
    'admin'             -- Level 5: 50,000+ points
);

CREATE TYPE transaction_type_enum AS ENUM (
    'registration_bonus',  -- +100 points on registration
    'create_post',         -- -5 points
    'create_comment',      -- -2 points
    'like_content',        -- -1 point
    'receive_like',        -- +3, +30, +350 based on milestones
    'crypto_reward',       -- -10,000 points for 0.01 BNB
    'admin_adjustment',    -- Manual points adjustment
    'refund'               -- Points refunded (unlike, delete)
);

CREATE TYPE report_status_enum AS ENUM (
    'pending',      -- Awaiting review
    'reviewing',    -- Under moderation review
    'resolved',     -- Action taken
    'dismissed',    -- No action needed
    'appealed'      -- User appealed the decision
);

CREATE TYPE report_reason_enum AS ENUM (
    'spam',
    'harassment',
    'hate_speech',
    'misinformation',
    'nsfw_content',
    'self_promotion',
    'copyright',
    'other'
);

CREATE TYPE oauth_provider_enum AS ENUM (
    'discord',
    'twitter',
    'telegram',
    'reddit',
    'facebook'
);

CREATE TYPE content_type_enum AS ENUM (
    'post',
    'comment'
);

CREATE TYPE media_type_enum AS ENUM (
    'image',
    'video',
    'avatar'
);

-- ============================================================================
-- TABLE: users
-- ============================================================================

CREATE TABLE users (
    id BIGSERIAL PRIMARY KEY,

    -- Authentication
    email VARCHAR(320) UNIQUE NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255),  -- NULL if OAuth-only user
    email_verified BOOLEAN DEFAULT FALSE,
    email_verification_token VARCHAR(255),
    email_verification_expires_at TIMESTAMPTZ,

    -- Profile
    display_name VARCHAR(100),
    bio TEXT,
    avatar_url TEXT,
    avatar_ipfs_hash VARCHAR(64),

    -- Reputation & Level
    points INT DEFAULT 0 CHECK (points >= 0),
    level user_level_enum DEFAULT 'new_user',
    total_posts_created INT DEFAULT 0,
    total_comments_created INT DEFAULT 0,
    total_likes_received INT DEFAULT 0,
    total_likes_given INT DEFAULT 0,

    -- Blockchain
    bnb_wallet_address VARCHAR(42),  -- Ethereum-compatible address (0x...)
    total_bnb_earned DECIMAL(18, 8) DEFAULT 0,

    -- Status
    is_active BOOLEAN DEFAULT TRUE,
    is_verified BOOLEAN DEFAULT FALSE,  -- Verified badge
    banned_until TIMESTAMPTZ,
    ban_reason TEXT,

    -- Preferences
    preferences JSONB DEFAULT '{}'::jsonb,  -- User settings (theme, notifications)

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,

    -- Indexes
    CONSTRAINT email_format CHECK (email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'),
    CONSTRAINT username_format CHECK (username ~* '^[A-Za-z0-9_-]{3,50}$'),
    CONSTRAINT bnb_address_format CHECK (
        bnb_wallet_address IS NULL OR
        bnb_wallet_address ~* '^0x[a-fA-F0-9]{40}$'
    )
);

COMMENT ON TABLE users IS 'Core user accounts with authentication, reputation, and blockchain data';
COMMENT ON COLUMN users.points IS 'Current point balance (earned - spent)';
COMMENT ON COLUMN users.level IS 'User level based on reputation (new_user to admin)';
COMMENT ON COLUMN users.bnb_wallet_address IS 'BNB Chain wallet address for crypto rewards';
COMMENT ON COLUMN users.preferences IS 'JSON object with user settings (theme, email notifications, etc.)';

-- ============================================================================
-- TABLE: oauth_accounts
-- ============================================================================

CREATE TABLE oauth_accounts (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- OAuth Provider
    provider oauth_provider_enum NOT NULL,
    oauth_id VARCHAR(255) NOT NULL,  -- Provider's user ID

    -- OAuth Data
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TIMESTAMPTZ,

    -- Profile Data from Provider
    profile_data JSONB DEFAULT '{}'::jsonb,  -- Store provider profile (avatar, bio, etc.)

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    UNIQUE(provider, oauth_id),  -- One OAuth account per provider per user
    UNIQUE(user_id, provider)    -- User can link each provider only once
);

COMMENT ON TABLE oauth_accounts IS 'OAuth2 social login accounts linked to users';
COMMENT ON COLUMN oauth_accounts.profile_data IS 'JSON object with provider profile data';

-- ============================================================================
-- TABLE: levels
-- ============================================================================

CREATE TABLE levels (
    id SERIAL PRIMARY KEY,
    name user_level_enum UNIQUE NOT NULL,
    min_points INT NOT NULL,
    max_points INT,

    -- Permissions
    can_create_post BOOLEAN DEFAULT TRUE,
    can_delete_own_post BOOLEAN DEFAULT TRUE,
    can_edit_own_post BOOLEAN DEFAULT TRUE,
    can_comment BOOLEAN DEFAULT TRUE,
    can_like BOOLEAN DEFAULT TRUE,
    can_report BOOLEAN DEFAULT FALSE,
    can_moderate BOOLEAN DEFAULT FALSE,
    can_ban_users BOOLEAN DEFAULT FALSE,
    can_manage_channels BOOLEAN DEFAULT FALSE,

    -- Rate Limits
    max_posts_per_day INT DEFAULT 50,
    max_comments_per_day INT DEFAULT 200,
    max_likes_per_hour INT DEFAULT 50,

    -- Display
    badge_color VARCHAR(7),  -- Hex color code
    badge_icon VARCHAR(50),  -- Emoji or icon name

    CONSTRAINT min_less_than_max CHECK (max_points IS NULL OR min_points < max_points)
);

COMMENT ON TABLE levels IS 'User level definitions with permissions and rate limits';

-- Insert default levels
INSERT INTO levels (name, min_points, max_points, can_report, can_moderate, can_ban_users, can_manage_channels, max_posts_per_day, badge_color, badge_icon) VALUES
('new_user', 0, 99, FALSE, FALSE, FALSE, FALSE, 5, '#94A3B8', '🌱'),
('active_user', 100, 499, TRUE, FALSE, FALSE, FALSE, 20, '#3B82F6', '⭐'),
('trusted_user', 500, 1999, TRUE, FALSE, FALSE, FALSE, 50, '#8B5CF6', '💎'),
('moderator', 2000, 9999, TRUE, TRUE, TRUE, FALSE, 100, '#F59E0B', '🛡️'),
('senior_moderator', 10000, 49999, TRUE, TRUE, TRUE, TRUE, 200, '#EF4444', '👑'),
('admin', 50000, NULL, TRUE, TRUE, TRUE, TRUE, 500, '#10B981', '🚀');

-- ============================================================================
-- TABLE: posts
-- ============================================================================

CREATE TABLE posts (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Content
    title VARCHAR(300) NOT NULL,
    body TEXT NOT NULL,
    body_html TEXT,  -- Rendered markdown HTML

    -- Metadata
    slug VARCHAR(350) UNIQUE,  -- URL-friendly title
    channel_id BIGINT,  -- FK added after channels table

    -- Engagement Metrics
    like_count INT DEFAULT 0,
    comment_count INT DEFAULT 0,
    view_count INT DEFAULT 0,

    -- Moderation
    is_deleted BOOLEAN DEFAULT FALSE,
    is_locked BOOLEAN DEFAULT FALSE,  -- No more comments allowed
    is_pinned BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT REFERENCES users(id),

    -- SEO
    meta_description VARCHAR(160),

    -- Search
    search_vector tsvector,  -- Full-text search index

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMPTZ,

    -- Constraints
    CONSTRAINT title_length CHECK (char_length(title) BETWEEN 10 AND 300),
    CONSTRAINT body_length CHECK (char_length(body) BETWEEN 10 AND 10000)
);

COMMENT ON TABLE posts IS 'Forum posts with markdown content and engagement metrics';
COMMENT ON COLUMN posts.body_html IS 'Pre-rendered HTML from markdown for performance';
COMMENT ON COLUMN posts.search_vector IS 'Full-text search index (auto-updated by trigger)';

-- ============================================================================
-- TABLE: comments
-- ============================================================================

CREATE TABLE comments (
    id BIGSERIAL PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    parent_id BIGINT REFERENCES comments(id) ON DELETE CASCADE,  -- For nested comments

    -- Content
    body TEXT NOT NULL,
    body_html TEXT,  -- Rendered markdown HTML

    -- Engagement Metrics
    like_count INT DEFAULT 0,

    -- Moderation
    is_deleted BOOLEAN DEFAULT FALSE,
    deleted_at TIMESTAMPTZ,
    deleted_by BIGINT REFERENCES users(id),

    -- Nesting
    depth INT DEFAULT 0,  -- 0 = top-level, 1 = reply, 2 = reply-to-reply

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    edited_at TIMESTAMPTZ,

    -- Constraints
    CONSTRAINT body_length CHECK (char_length(body) BETWEEN 1 AND 2000),
    CONSTRAINT max_depth CHECK (depth <= 2)  -- Max 2 levels of nesting
);

COMMENT ON TABLE comments IS 'Nested comments on posts (max 2 levels deep)';
COMMENT ON COLUMN comments.parent_id IS 'NULL for top-level comments, references parent comment for replies';
COMMENT ON COLUMN comments.depth IS 'Nesting depth: 0 = top-level, 1 = reply, 2 = reply-to-reply';

-- ============================================================================
-- TABLE: likes
-- ============================================================================

CREATE TABLE likes (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Polymorphic relationship (either post_id OR comment_id)
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES comments(id) ON DELETE CASCADE,

    -- Metadata
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT like_target CHECK (
        (post_id IS NOT NULL AND comment_id IS NULL) OR
        (post_id IS NULL AND comment_id IS NOT NULL)
    ),
    CONSTRAINT unique_post_like UNIQUE NULLS NOT DISTINCT (user_id, post_id),
    CONSTRAINT unique_comment_like UNIQUE NULLS NOT DISTINCT (user_id, comment_id)
);

COMMENT ON TABLE likes IS 'User likes on posts and comments (1 like per user per content)';
COMMENT ON CONSTRAINT like_target ON likes IS 'Ensure like is on either post or comment, not both';

-- ============================================================================
-- TABLE: transactions
-- ============================================================================

CREATE TABLE transactions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Transaction Details
    amount INT NOT NULL,  -- Positive for earn, negative for spend
    type transaction_type_enum NOT NULL,
    description TEXT,

    -- Reference to related content
    reference_type content_type_enum,
    reference_id BIGINT,  -- Post ID, Comment ID, etc.

    -- Metadata
    metadata JSONB DEFAULT '{}'::jsonb,  -- Additional transaction data

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE transactions IS 'Audit trail for all point transactions (earn and spend)';
COMMENT ON COLUMN transactions.amount IS 'Positive for earning, negative for spending';
COMMENT ON COLUMN transactions.reference_id IS 'ID of related post/comment/etc.';

-- ============================================================================
-- TABLE: media
-- ============================================================================

CREATE TABLE media (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Polymorphic relationship
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    comment_id BIGINT REFERENCES comments(id) ON DELETE CASCADE,

    -- File Details
    file_name VARCHAR(255) NOT NULL,
    file_size BIGINT NOT NULL,  -- Bytes
    mime_type VARCHAR(100) NOT NULL,
    media_type media_type_enum NOT NULL,

    -- Storage
    ipfs_hash VARCHAR(64) NOT NULL,  -- IPFS CID
    ipfs_url TEXT NOT NULL,          -- Full IPFS URL (https://gateway/ipfs/{cid})

    -- Image Metadata
    width INT,
    height INT,
    alt_text TEXT,  -- Accessibility

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT file_size_limit CHECK (file_size <= 10485760),  -- 10MB max
    CONSTRAINT image_dimensions CHECK (
        (width IS NULL AND height IS NULL) OR
        (width > 0 AND height > 0)
    )
);

COMMENT ON TABLE media IS 'IPFS-stored media files (images, videos, avatars)';
COMMENT ON COLUMN media.ipfs_hash IS 'IPFS Content Identifier (CID)';
COMMENT ON COLUMN media.file_size IS 'File size in bytes (max 10MB)';

-- ============================================================================
-- TABLE: reports
-- ============================================================================

CREATE TABLE reports (
    id BIGSERIAL PRIMARY KEY,
    reporter_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Reported Content
    content_type content_type_enum NOT NULL,
    content_id BIGINT NOT NULL,  -- Post ID or Comment ID
    reported_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Report Details
    reason report_reason_enum NOT NULL,
    description TEXT,

    -- Moderation
    status report_status_enum DEFAULT 'pending',
    reviewed_by BIGINT REFERENCES users(id),
    reviewed_at TIMESTAMPTZ,
    resolution_notes TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT description_length CHECK (char_length(description) <= 1000)
);

COMMENT ON TABLE reports IS 'User reports for spam, harassment, and policy violations';
COMMENT ON COLUMN reports.content_id IS 'ID of reported post or comment';
COMMENT ON COLUMN reports.reported_user_id IS 'User who created the reported content';

-- ============================================================================
-- TABLE: bans
-- ============================================================================

CREATE TABLE bans (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Ban Details
    reason TEXT NOT NULL,
    banned_by BIGINT NOT NULL REFERENCES users(id),
    banned_until TIMESTAMPTZ,  -- NULL for permanent ban
    is_permanent BOOLEAN DEFAULT FALSE,

    -- Appeal
    appeal_text TEXT,
    appeal_status report_status_enum,
    appeal_reviewed_by BIGINT REFERENCES users(id),
    appeal_reviewed_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT reason_length CHECK (char_length(reason) BETWEEN 10 AND 1000)
);

COMMENT ON TABLE bans IS 'User bans (temporary or permanent) by moderators';
COMMENT ON COLUMN bans.banned_until IS 'NULL for permanent ban, timestamp for temporary';

-- ============================================================================
-- TABLE: channels
-- ============================================================================

CREATE TABLE channels (
    id BIGSERIAL PRIMARY KEY,

    -- Channel Details
    name VARCHAR(50) UNIQUE NOT NULL,
    slug VARCHAR(50) UNIQUE NOT NULL,
    description TEXT,

    -- Metadata
    icon VARCHAR(50),  -- Emoji or icon name
    color VARCHAR(7),  -- Hex color code

    -- Moderation
    created_by BIGINT REFERENCES users(id),
    moderators BIGINT[],  -- Array of user IDs with mod permissions

    -- Stats
    post_count INT DEFAULT 0,
    subscriber_count INT DEFAULT 0,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT name_length CHECK (char_length(name) BETWEEN 3 AND 50),
    CONSTRAINT slug_format CHECK (slug ~* '^[a-z0-9-]+$')
);

COMMENT ON TABLE channels IS 'Forum channels/categories for organizing posts';
COMMENT ON COLUMN channels.moderators IS 'Array of user IDs with moderator permissions for this channel';

-- Add FK to posts after channels table exists
ALTER TABLE posts ADD CONSTRAINT fk_posts_channel FOREIGN KEY (channel_id) REFERENCES channels(id) ON DELETE SET NULL;

-- ============================================================================
-- TABLE: tags
-- ============================================================================

CREATE TABLE tags (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL,
    slug VARCHAR(50) UNIQUE NOT NULL,
    post_count INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT tag_format CHECK (name ~* '^[a-z0-9-]+$')
);

COMMENT ON TABLE tags IS 'Tags for categorizing posts (many-to-many with posts)';

-- ============================================================================
-- TABLE: post_tags (Junction Table)
-- ============================================================================

CREATE TABLE post_tags (
    post_id BIGINT NOT NULL REFERENCES posts(id) ON DELETE CASCADE,
    tag_id BIGINT NOT NULL REFERENCES tags(id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (post_id, tag_id)
);

COMMENT ON TABLE post_tags IS 'Many-to-many relationship between posts and tags';

-- ============================================================================
-- TABLE: sessions
-- ============================================================================

CREATE TABLE sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Session Data
    session_token VARCHAR(255) UNIQUE NOT NULL,
    ip_address INET,
    user_agent TEXT,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    last_activity_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,

    -- Constraints
    CONSTRAINT expires_after_created CHECK (expires_at > created_at)
);

COMMENT ON TABLE sessions IS 'User sessions for authentication (7-day TTL)';
COMMENT ON COLUMN sessions.session_token IS 'Secure random token stored in HttpOnly cookie';

-- ============================================================================
-- TABLE: notifications
-- ============================================================================

CREATE TABLE notifications (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Notification Details
    type VARCHAR(50) NOT NULL,  -- 'like', 'comment', 'reply', 'mention', 'level_up'
    title VARCHAR(255) NOT NULL,
    message TEXT,

    -- Reference to related content
    reference_type content_type_enum,
    reference_id BIGINT,

    -- Related User
    actor_id BIGINT REFERENCES users(id) ON DELETE CASCADE,  -- User who triggered notification

    -- Status
    is_read BOOLEAN DEFAULT FALSE,
    read_at TIMESTAMPTZ,

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

COMMENT ON TABLE notifications IS 'User notifications for likes, comments, mentions, etc.';
COMMENT ON COLUMN notifications.actor_id IS 'User who triggered the notification (liker, commenter, etc.)';

-- ============================================================================
-- TABLE: blockchain_transactions
-- ============================================================================

CREATE TABLE blockchain_transactions (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,

    -- Transaction Details
    transaction_hash VARCHAR(66) UNIQUE NOT NULL,  -- 0x + 64 hex chars
    amount_bnb DECIMAL(18, 8) NOT NULL,
    points_spent INT NOT NULL,

    -- Status
    status VARCHAR(20) DEFAULT 'pending',  -- 'pending', 'confirmed', 'failed'
    block_number BIGINT,
    confirmations INT DEFAULT 0,

    -- Gas
    gas_used BIGINT,
    gas_price_gwei DECIMAL(18, 9),

    -- Timestamps
    created_at TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP,
    confirmed_at TIMESTAMPTZ,

    -- Constraints
    CONSTRAINT tx_hash_format CHECK (transaction_hash ~* '^0x[a-fA-F0-9]{64}$')
);

COMMENT ON TABLE blockchain_transactions IS 'BNB Chain reward distributions (10,000 points → 0.01 BNB)';
COMMENT ON COLUMN blockchain_transactions.transaction_hash IS 'BNB Chain transaction hash';
COMMENT ON COLUMN blockchain_transactions.amount_bnb IS 'BNB amount sent (typically 0.01)';

-- ============================================================================
-- INDEXES
-- ============================================================================

-- Users
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_username ON users(username);
CREATE INDEX idx_users_level ON users(level);
CREATE INDEX idx_users_points ON users(points DESC);
CREATE INDEX idx_users_created_at ON users(created_at DESC);
CREATE INDEX idx_users_active ON users(id) WHERE is_active = TRUE AND banned_until IS NULL;
CREATE INDEX idx_users_username_trgm ON users USING GIN(username gin_trgm_ops);  -- Fuzzy search

-- Posts
CREATE INDEX idx_posts_user_id ON posts(user_id);
CREATE INDEX idx_posts_channel_id ON posts(channel_id);
CREATE INDEX idx_posts_created_at ON posts(created_at DESC);
CREATE INDEX idx_posts_like_count ON posts(like_count DESC);
CREATE INDEX idx_posts_trending ON posts((like_count * 10 + comment_count * 5) / EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - created_at)));
CREATE INDEX idx_posts_search ON posts USING GIN(search_vector);  -- Full-text search
CREATE INDEX idx_posts_slug ON posts(slug);
CREATE INDEX idx_posts_active ON posts(id) WHERE is_deleted = FALSE;

-- Comments
CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_user_id ON comments(user_id);
CREATE INDEX idx_comments_parent_id ON comments(parent_id);
CREATE INDEX idx_comments_created_at ON comments(created_at DESC);
CREATE INDEX idx_comments_active ON comments(id) WHERE is_deleted = FALSE;

-- Likes
CREATE INDEX idx_likes_user_id ON likes(user_id);
CREATE INDEX idx_likes_post_id ON likes(post_id);
CREATE INDEX idx_likes_comment_id ON likes(comment_id);
CREATE INDEX idx_likes_created_at ON likes(created_at DESC);

-- Transactions
CREATE INDEX idx_transactions_user_id ON transactions(user_id);
CREATE INDEX idx_transactions_type ON transactions(type);
CREATE INDEX idx_transactions_created_at ON transactions(created_at DESC);
CREATE INDEX idx_transactions_reference ON transactions(reference_type, reference_id);

-- Reports
CREATE INDEX idx_reports_reporter_id ON reports(reporter_id);
CREATE INDEX idx_reports_reported_user_id ON reports(reported_user_id);
CREATE INDEX idx_reports_status ON reports(status);
CREATE INDEX idx_reports_created_at ON reports(created_at DESC);

-- Sessions
CREATE INDEX idx_sessions_user_id ON sessions(user_id);
CREATE INDEX idx_sessions_token ON sessions(session_token);
CREATE INDEX idx_sessions_expires_at ON sessions(expires_at);

-- Notifications
CREATE INDEX idx_notifications_user_id ON notifications(user_id);
CREATE INDEX idx_notifications_unread ON notifications(user_id) WHERE is_read = FALSE;
CREATE INDEX idx_notifications_created_at ON notifications(created_at DESC);

-- Blockchain Transactions
CREATE INDEX idx_blockchain_tx_user_id ON blockchain_transactions(user_id);
CREATE INDEX idx_blockchain_tx_status ON blockchain_transactions(status);
CREATE INDEX idx_blockchain_tx_hash ON blockchain_transactions(transaction_hash);

-- ============================================================================
-- TRIGGERS
-- ============================================================================

-- Trigger: Update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_users_updated_at BEFORE UPDATE ON users
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON posts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_comments_updated_at BEFORE UPDATE ON comments
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_reports_updated_at BEFORE UPDATE ON reports
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_oauth_accounts_updated_at BEFORE UPDATE ON oauth_accounts
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Trigger: Update post like_count when like is added/removed
CREATE OR REPLACE FUNCTION update_post_like_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE posts SET like_count = like_count + 1 WHERE id = NEW.post_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE posts SET like_count = like_count - 1 WHERE id = OLD.post_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_post_like_count_trigger
AFTER INSERT OR DELETE ON likes
FOR EACH ROW
WHEN (NEW.post_id IS NOT NULL OR OLD.post_id IS NOT NULL)
EXECUTE FUNCTION update_post_like_count();

-- Trigger: Update comment like_count when like is added/removed
CREATE OR REPLACE FUNCTION update_comment_like_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE comments SET like_count = like_count + 1 WHERE id = NEW.comment_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE comments SET like_count = like_count - 1 WHERE id = OLD.comment_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_comment_like_count_trigger
AFTER INSERT OR DELETE ON likes
FOR EACH ROW
WHEN (NEW.comment_id IS NOT NULL OR OLD.comment_id IS NOT NULL)
EXECUTE FUNCTION update_comment_like_count();

-- Trigger: Update post comment_count when comment is added/removed
CREATE OR REPLACE FUNCTION update_post_comment_count()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE posts SET comment_count = comment_count + 1 WHERE id = NEW.post_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE posts SET comment_count = comment_count - 1 WHERE id = OLD.post_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_post_comment_count_trigger
AFTER INSERT OR DELETE ON comments
FOR EACH ROW
EXECUTE FUNCTION update_post_comment_count();

-- Trigger: Update user stats when post/comment is created
CREATE OR REPLACE FUNCTION update_user_stats_on_post()
RETURNS TRIGGER AS $$
BEGIN
    IF TG_OP = 'INSERT' THEN
        UPDATE users SET total_posts_created = total_posts_created + 1 WHERE id = NEW.user_id;
    ELSIF TG_OP = 'DELETE' THEN
        UPDATE users SET total_posts_created = total_posts_created - 1 WHERE id = OLD.user_id;
    END IF;
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_user_stats_on_post_trigger
AFTER INSERT OR DELETE ON posts
FOR EACH ROW
EXECUTE FUNCTION update_user_stats_on_post();

-- Trigger: Update full-text search vector for posts
CREATE OR REPLACE FUNCTION update_post_search_vector()
RETURNS TRIGGER AS $$
BEGIN
    NEW.search_vector := to_tsvector('english', COALESCE(NEW.title, '') || ' ' || COALESCE(NEW.body, ''));
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_post_search_vector_trigger
BEFORE INSERT OR UPDATE ON posts
FOR EACH ROW
EXECUTE FUNCTION update_post_search_vector();

-- Trigger: Auto-generate post slug from title
CREATE OR REPLACE FUNCTION generate_post_slug()
RETURNS TRIGGER AS $$
DECLARE
    base_slug TEXT;
    final_slug TEXT;
    counter INT := 1;
BEGIN
    -- Generate base slug from title
    base_slug := regexp_replace(lower(NEW.title), '[^a-z0-9]+', '-', 'g');
    base_slug := regexp_replace(base_slug, '^-+|-+$', '', 'g');  -- Remove leading/trailing hyphens
    base_slug := substring(base_slug from 1 for 300);  -- Limit to 300 chars

    final_slug := base_slug;

    -- Check for duplicates and append counter if needed
    WHILE EXISTS (SELECT 1 FROM posts WHERE slug = final_slug AND id != COALESCE(NEW.id, 0)) LOOP
        final_slug := base_slug || '-' || counter;
        counter := counter + 1;
    END LOOP;

    NEW.slug := final_slug;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER generate_post_slug_trigger
BEFORE INSERT OR UPDATE OF title ON posts
FOR EACH ROW
EXECUTE FUNCTION generate_post_slug();

-- Trigger: Calculate user level based on points
CREATE OR REPLACE FUNCTION calculate_user_level()
RETURNS TRIGGER AS $$
BEGIN
    NEW.level := CASE
        WHEN NEW.points >= 50000 THEN 'admin'::user_level_enum
        WHEN NEW.points >= 10000 THEN 'senior_moderator'::user_level_enum
        WHEN NEW.points >= 2000 THEN 'moderator'::user_level_enum
        WHEN NEW.points >= 500 THEN 'trusted_user'::user_level_enum
        WHEN NEW.points >= 100 THEN 'active_user'::user_level_enum
        ELSE 'new_user'::user_level_enum
    END;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER calculate_user_level_trigger
BEFORE INSERT OR UPDATE OF points ON users
FOR EACH ROW
EXECUTE FUNCTION calculate_user_level();

-- ============================================================================
-- VIEWS
-- ============================================================================

-- View: Active users with reputation
CREATE VIEW v_active_users AS
SELECT
    u.id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.points,
    u.level,
    u.total_posts_created,
    u.total_comments_created,
    u.total_likes_received,
    u.is_verified,
    u.created_at
FROM users u
WHERE u.is_active = TRUE
  AND u.banned_until IS NULL
ORDER BY u.points DESC;

COMMENT ON VIEW v_active_users IS 'Active users sorted by reputation points';

-- View: Trending posts (hot algorithm)
CREATE VIEW v_trending_posts AS
SELECT
    p.*,
    u.username AS author_username,
    u.avatar_url AS author_avatar,
    u.level AS author_level,
    (p.like_count * 10 + p.comment_count * 5) /
        NULLIF(EXTRACT(EPOCH FROM (CURRENT_TIMESTAMP - p.created_at)) / 3600, 0) AS trending_score
FROM posts p
JOIN users u ON p.user_id = u.id
WHERE p.is_deleted = FALSE
  AND p.created_at > CURRENT_TIMESTAMP - INTERVAL '7 days'
ORDER BY trending_score DESC;

COMMENT ON VIEW v_trending_posts IS 'Trending posts using hot algorithm (likes + comments / time)';

-- View: Leaderboard
CREATE VIEW v_leaderboard AS
SELECT
    u.id,
    u.username,
    u.display_name,
    u.avatar_url,
    u.points,
    u.level,
    u.total_posts_created,
    u.total_comments_created,
    u.total_likes_received,
    u.total_bnb_earned,
    RANK() OVER (ORDER BY u.points DESC) AS rank
FROM users u
WHERE u.is_active = TRUE
  AND u.banned_until IS NULL
ORDER BY u.points DESC
LIMIT 100;

COMMENT ON VIEW v_leaderboard IS 'Top 100 users by reputation points';

-- ============================================================================
-- FUNCTIONS
-- ============================================================================

-- Function: Get user balance
CREATE OR REPLACE FUNCTION get_user_balance(p_user_id BIGINT)
RETURNS INT AS $$
DECLARE
    balance INT;
BEGIN
    SELECT points INTO balance FROM users WHERE id = p_user_id;
    RETURN COALESCE(balance, 0);
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION get_user_balance IS 'Get current point balance for a user';

-- Function: Search posts (full-text search)
CREATE OR REPLACE FUNCTION search_posts(p_query TEXT, p_limit INT DEFAULT 20)
RETURNS TABLE (
    id BIGINT,
    title VARCHAR(300),
    body TEXT,
    like_count INT,
    comment_count INT,
    created_at TIMESTAMPTZ,
    rank REAL
) AS $$
BEGIN
    RETURN QUERY
    SELECT
        p.id,
        p.title,
        p.body,
        p.like_count,
        p.comment_count,
        p.created_at,
        ts_rank(p.search_vector, plainto_tsquery('english', p_query)) AS rank
    FROM posts p
    WHERE p.search_vector @@ plainto_tsquery('english', p_query)
      AND p.is_deleted = FALSE
    ORDER BY rank DESC, p.created_at DESC
    LIMIT p_limit;
END;
$$ LANGUAGE plpgsql STABLE;

COMMENT ON FUNCTION search_posts IS 'Full-text search for posts using PostgreSQL tsvector';

-- ============================================================================
-- SAMPLE DATA (For Development)
-- ============================================================================

-- Insert sample channels
INSERT INTO channels (name, slug, description, icon, color) VALUES
('General', 'general', 'General discussion about crypto and blockchain', '💬', '#3B82F6'),
('BNB Chain', 'bnb-chain', 'Discussions about BNB Chain ecosystem', '🔶', '#F3BA2F'),
('DeFi', 'defi', 'Decentralized Finance protocols and strategies', '💰', '#10B981'),
('NFTs', 'nfts', 'Non-Fungible Tokens and digital collectibles', '🎨', '#8B5CF6'),
('Trading', 'trading', 'Trading strategies, technical analysis, and market discussion', '📈', '#EF4444');

-- Insert sample tags
INSERT INTO tags (name, slug) VALUES
('bnb', 'bnb'),
('defi', 'defi'),
('nft', 'nft'),
('tutorial', 'tutorial'),
('news', 'news'),
('question', 'question'),
('discussion', 'discussion'),
('pancakeswap', 'pancakeswap');

-- ============================================================================
-- SCHEMA VALIDATION QUERIES
-- ============================================================================

-- Count tables
SELECT COUNT(*) AS total_tables
FROM information_schema.tables
WHERE table_schema = 'public' AND table_type = 'BASE TABLE';
-- Expected: 18 tables

-- Count indexes
SELECT COUNT(*) AS total_indexes
FROM pg_indexes
WHERE schemaname = 'public';
-- Expected: 40+ indexes

-- Count triggers
SELECT COUNT(*) AS total_triggers
FROM information_schema.triggers
WHERE trigger_schema = 'public';
-- Expected: 10+ triggers

-- Count views
SELECT COUNT(*) AS total_views
FROM information_schema.views
WHERE table_schema = 'public';
-- Expected: 3 views

-- ============================================================================
-- BACKUP & MAINTENANCE
-- ============================================================================

-- Daily backup command (run via cron)
-- pg_dump -U user -d forum -F c -b -v -f backup_$(date +%Y%m%d).dump

-- Analyze tables for query optimization
ANALYZE;

-- Vacuum to reclaim space
VACUUM ANALYZE;

-- ============================================================================
-- END OF SCHEMA
-- ============================================================================
